"""Miscellaneous constants supporting the development of spells."""

STARTING_FP: int = 10

SPELL_BASE_ADDRESS: int = 0x3A20F1
SPELL_BASE_NAME_ADDRESS: int = 0x3A137F
SPELL_BASE_DESC_ADDRESS: int = 0x3A2B80

SPELL_TIMING_MODIFIERS_BASE_ADDRESS: int = 0x02CACE
SPELL_DAMAGE_MODIFIERS_BASE_ADDRESS: int = 0x02D05B

ALLY_SPELL_POINTER_TABLE_START: int = 0x35C992
