# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py roomdisassembler --rom ROM
from smrpgpatchbuilder.datatypes.levels.classes import ObjectType, EventInitiator, PostBattleBehaviour, Direction, EdgeDirection, ExitType, BufferType, BufferSpace, VramStore, ShadowSize
from smrpgpatchbuilder.datatypes.levels.classes import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from randomizer.data.rooms import npcs
from disassembler_output.variables import room_names, overworld_area_names, music_names
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=False,
        extra_sprite_buffer_size=0,
        buffers = [
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=music_names.M0032_ANDMYNAME_SBOOSTER,
    entrance_event=2417,
    exit_fields=[
        RoomExit(
            x=11,
            y=127,
            z=5,
            f=EdgeDirection.SOUTHEAST,
            length=2,
            height=0,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=room_names.R038_BOOSTER_TOWER_9F_BOOSTERS_BOMBTHROWING_ROOM_WRAIL_TRACKS,
            show_message=False,
            dst_x=11,
            dst_y=81,
            dst_z=0,
            dst_z_half=0,
            dst_f=Direction.1,
            x_bit_7=False,
        ),
        RoomExit(
            x=16,
            y=125,
            z=0,
            f=EdgeDirection.SOUTHEAST,
            length=2,
            height=0,
            nw_se_edge_active=True,
            ne_sw_edge_active=False,
            byte_2_bit_2=False,
            destination=room_names.R041_BOOSTER_TOWER_8F_AREA_01_MINESWEEPER_ROOM_WCOINS_AND_HIDDEN_FIREBALLS,
            show_message=False,
            dst_x=21,
            dst_y=21,
            dst_z=0,
            dst_z_half=0,
            dst_f=Direction.1,
            x_bit_7=False,
        ),
    ],
    objects=[
        BattlePackNPC( # 0
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106c0c150>,
            initiator=EventInitiator.ANYTHING_EXCEPT_PRESS_A,
            after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
            battle_pack=50,
            action_script=703,
            visible=True,
            x=14,
            y=119,
            z=2,
            z_half=False,
            direction=Direction.3,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=True,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=True,
            cant_move_if_in_air=False,
            byte7_upper2=3,
        ),
        BattlePackClone( # 1
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106c0c150>,
            battle_pack=50,
            action_script=703,
            visible=True,
            x=14,
            y=117,
            z=4,
            z_half=False,
            direction=Direction.1,
        ),
        BattlePackClone( # 2
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106c0c150>,
            battle_pack=50,
            action_script=703,
            visible=True,
            x=11,
            y=122,
            z=5,
            z_half=False,
            direction=Direction.7,
        ),
    ]
)
