# AUTOGENERATED DO NOT EDIT!!
# Run the following command if you need to rebuild the table
# python manage.py roomdisassembler --rom ROM
from smrpgpatchbuilder.datatypes.levels.classes import ObjectType, EventInitiator, PostBattleBehaviour, Direction, EdgeDirection, ExitType, BufferType, BufferSpace, VramStore, ShadowSize
from smrpgpatchbuilder.datatypes.levels.classes import Buffer, Partition, DestinationProps, RoomExit, MapExit, Event, BattlePackNPC, RegularNPC, ChestNPC, BattlePackClone, RegularClone, ChestClone, Room
from randomizer.data.rooms import npcs
from disassembler_output.variables import room_names, overworld_area_names, music_names
room = Room(
    partition=Partition(
        ally_sprite_buffer_size=1,
        allow_extra_sprite_buffer=True,
        extra_sprite_buffer_size=1,
        buffers = [
            Buffer(
                buffer_type=BufferType.THREE_SPRITES_PER_ROW,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            ),
            Buffer(
                buffer_type=BufferType.EMPTY_3,
                main_buffer_space=BufferSpace.BYTES_0,
                index_in_main_buffer=True
            )
        ],
        full_palette_buffer=True
    ),
    music=music_names.M0000_CURRENT,
    entrance_event=15,
    objects=[
        RegularNPC( # 0
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106bf8750>,
            initiator=EventInitiator.NONE,
            event_script=256,
            action_script=15,
            visible=True,
            x=25,
            y=28,
            z=9,
            z_half=False,
            direction=Direction.3,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=True,
            byte7_upper2=3,
        ),
        BattlePackNPC( # 1
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106bf8750>,
            initiator=EventInitiator.NONE,
            after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
            battle_pack=34,
            action_script=15,
            visible=True,
            x=29,
            y=20,
            z=6,
            z_half=False,
            direction=Direction.3,
            face_on_trigger=False,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=True,
            cant_walk_up_stairs=False,
            cant_walk_under=False,
            cant_pass_walls=False,
            cant_jump_through=False,
            cant_pass_npcs=True,
            byte3_bit5=True,
            cant_walk_through=True,
            byte3_bit7=False,
            slidable_along_walls=False,
            cant_move_if_in_air=True,
            byte7_upper2=3,
        ),
        BattlePackNPC( # 2
            npc=<smrpgpatchbuilder.datatypes.levels.classes.NPC object at 0x106bf8750>,
            initiator=EventInitiator.NONE,
            after_battle=PostBattleBehaviour.REMOVE_PERMANENTLY,
            battle_pack=7,
            action_script=15,
            visible=True,
            x=28,
            y=21,
            z=7,
            z_half=False,
            direction=Direction.3,
            face_on_trigger=True,
            cant_enter_doors=False,
            byte2_bit5=False,
            set_sequence_playback=True,
            cant_float=False,
            cant_walk_up_stairs=False,
            cant_walk_under=True,
            cant_pass_walls=True,
            cant_jump_through=False,
            cant_pass_npcs=False,
            byte3_bit5=False,
            cant_walk_through=False,
            byte3_bit7=False,
            slidable_along_walls=True,
            cant_move_if_in_air=False,
            byte7_upper2=3,
        ),
    ]
)
