"""Class instances for arguments needing special restrictions that are used by spells."""

from .damage_modifiers import (
    NO_MODIFIERS,
    X00625_MODIFIER,
    X05_MODIFIER,
    X0125_MODIFIER_WITH_MULTI_TARGETING,
    X00625_MODIFIER_WITH_MULTI_TARGETING,
)

from .timing_properties import (
    ONE_TIMING_FOR_125_OR_15X_DMG,
    MULTIPLE_BUTTON_PRESSES,
    ONE_PLUS_MORE_TARGETS_WITH_PRESSES,
    ONE_TIMING_FOR_125_DMG_ONLY,
    ROTATE_1_TARGET_IF_TIMED_ALL,
    TIMED_HEALS_ALL_HP_TO_FIRST_TARGET,
    BUTTON_MASH,
    ROTATE_ONLY,
    CHARGE_ONLY,
    TIMED_GIVES_TARGET_DEFENSE_UP_BUFF,
    TIMED_FOR_9999_SET_ENEMY_HP_0,
    TIME_TO_ACTIVATE_HP_READ,
    TIMED_JUMPS,
)
